server:
  port: 8768
spring:
  application:
    name: congif
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xinbinxuan1/config-talents.git
          search-paths: /
          username:
          password:
          skip-ssl-validation: true
        label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka