server:
  port: 8768
spring:
  application:
    name: congif
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xinbinxuan1/config-talents.git
          search-paths: /
          username:
          password:
          skip-ssl-validation: true
        label: master
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
    sleuth:
      sampler:
        probability: 1
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka