
server:
  port: 8777

spring:
  application:
    name: logrecevie
  data:
    mongodb:
      host: 192.168.2.22
      port: 27017
      database: 1904a
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
